# Generated by Django 3.1 on 2020-12-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('hero', models.CharField(max_length=20)),
                ('heroine', models.CharField(max_length=30)),
                ('releasedate', models.DateField()),
            ],
        ),
    ]
